# Generated by Django 2.1.4 on 2018-12-10 05:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LearningContent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='example_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='image_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='definition',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
